### PR TITLE
Remove Gulp FTP.

### PR DESCRIPTION
**Pull request by DevJMD**

### CODE REVIEW

**Comment by jameshoward** [comment]
Wonder why I can't auto-merge this and would have to do it command line. Is it because your fork is out-of-date? Doesn't look like it is.

**Comment by DevJMD** [comment]
I was thinking this myself, but it's saying I'm up-to-date with the master repo.

**Comment by jameshoward** [comment]
It's because of a merge conflict in `app/templates/gulp/gulpfile.js`:

```
var concat       = require('gulp-concat'),
    uglify       = require('gulp-uglify'),
    jshint       = require('gulp-jshint'),
    rename       = require('gulp-rename'),
    swig         = require('gulp-swig'),
    sass         = require('gulp-sass'),
    autoprefixer = require('gulp-autoprefixer'),
    minifycss    = require('gulp-minify-css'),
    imagemin     = require('gulp-imagemin'),
    newer        = require('gulp-newer'),
<<<<<<< HEAD
    insert       = require('gulp-insert'),
    livereload   = require('gulp-livereload'),
    ftp          = require('gulp-ftp');
=======
    livereload   = require('gulp-livereload');
>>>>>>> e5fb6901835cc6abd4da2e023b1fada91ebd0ff8
```

**Comment by DevJMD** [comment]
Let me reset the upstream and I'll commit the merge.

**Comment by DevJMD** [comment]
@jameshoward, resolved. :+1:

**Comment by jameshoward** [comment]
Better, thanks!

**Pull request merged**
